---
hostname: deligoez-mac
git_email: ye@deligoz.me
timezone: Europe/Istanbul
region: TR
languages:
  - en-TR
  - tr-TR
  - de-DE
keyboard_layouts:
  - name: ABC
    id: 252
  - name: Turkish-QWERTY-PC
    id: -36
  - name: German
    id: 3
