---
- name: Initialize chezmoi
  ansible.builtin.command:
    cmd: /opt/homebrew/bin/chezmoi init --source={{ playbook_dir }}/../home --apply
  environment:
    PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:{{ ansible_facts.env.PATH }}"
  register: chezmoi_init
  changed_when: chezmoi_init.rc == 0
  ignore_errors: true

- name: Apply chezmoi configs
  ansible.builtin.command:
    cmd: /opt/homebrew/bin/chezmoi apply --source={{ playbook_dir }}/../home --force
  environment:
    PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:{{ ansible_facts.env.PATH }}"
  register: chezmoi_apply
  changed_when: chezmoi_apply.stderr | default('') | length > 0
  ignore_errors: true
