---
- name: Load Composer packages list
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../composer-packages.yml"

- name: Check installed Composer global packages
  ansible.builtin.command: /opt/homebrew/bin/composer global show {{ item }} --no-interaction
  environment:
    PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:{{ ansible_facts.env.PATH }}"
  register: composer_check
  changed_when: false
  failed_when: false
  loop: "{{ composer_packages }}"

- name: Install missing Composer global packages
  ansible.builtin.command: /opt/homebrew/bin/composer global require {{ item.item }} --no-interaction
  environment:
    PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:{{ ansible_facts.env.PATH }}"
  loop: "{{ composer_check.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: item.rc != 0
  changed_when: true
